# Generated by Django 5.2.3 on 2025-06-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmodel',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
